---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: flm
spec:
  replicase: 3
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata: 
      labels: 
        app: swiggy
    spec: 
      containers: 
        - name: container1
          image: shaikmustafa/cycle
          ports: 
            - containerPort: 80
